
// USER FUNCTIONS

//create profile
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
     "authId": "gdxT0S0hYKe8Dmual1ndjiRB5Ll1",
      "username": "Johan",
      "phone": "321-567-3423",
      "membership": "User"
}

###

//update profile
PUT http://localhost:5000/api/users/gdxT0S0hYKe8Dmual1ndjiRB5Ll1 HTTP/1.1
content-type: application/json

{
     "authId": "gdxT0S0hYKe8Dmual1ndjiRB5Ll1",
      "username": "Nohan"
}

###

//get all users
GET http://localhost:5000/api/users/getAll

###

// HOUSE FUNCTIONS

//create house

POST http://localhost:5000/api/houses/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1
content-type: application/json

{
      "authId": "kCd8oHU8VIcdtzcCbg3ARydWeMl1",
      "description": "This is my first house",
      "address":"134 Palm Bay Road",
      "zipCode": "32908"
}

###

//get house

GET http://localhost:5000/api/houses/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1

###

//update house
PUT http://localhost:5000/api/houses/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1
content-type: application/json

{
      "authId": "kCd8oHU8VIcdtzcCbg3ARydWeMl1",
      "description": "This is my first house",
      "address":"133 Palm Bay Road",
      "zipCode": "32908",
      "information":{
            "poolDesc": "900 gallon pool"
      }

}

###

//add user to house

PUT http://localhost:5000/api/houses/addUser/6199b3e741ec7decb28cd8c6 HTTP/1.1
content-type: application/json

{
      "authId": "f66sKE5aidWldUY0e7sCXElw0tH3",
      "dbId":"6199b3e741ec7decb28cd8c6"
}

###

//get all housemates of house

GET http://localhost:5000/api/houses/houseMates/O2lTRTw8lSbSSDvVmy481aF3ZDc2 HTTP/1.1

###

//get rid of housemate

DELETE http://localhost:5000/api/houses/6199b3e741ec7decb28cd8c6 HTTP/1.1
content-type: application/json

{
      "authId": "O2lTRTw8lSbSSDvVmy481aF3ZDc2",
      "dbId":"6199b3e741ec7decb28cd8c6"

}

###

//POST FUNCTIONS

//create post

POST http://localhost:5000/api/posts/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1
content-type: application/json

{
      "authId": "kCd8oHU8VIcdtzcCbg3ARydWeMl1",
      "title": "New turltle",
      "description": "We have some new turtles"
}

###

//get post

GET http://localhost:5000/api/posts/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1

###

//update post
PUT http://localhost:5000/api/posts/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1
content-type: application/json

{
      "postId": "61a02bccd52670e8aec982c5",
      "authId": "kCd8oHU8VIcdtzcCbg3ARydWeMl1",
      "title": "New Pangolin",
      "description": "Hey everyone, the game is on Thursday and we have a Pangolin!"
}

###

//delete post 

DELETE http://localhost:5000/api/posts/kCd8oHU8VIcdtzcCbg3ARydWeMl1 HTTP/1.1
content-type: application/json

{
      "postId": "61a02bccd52670e8aec982c5",
      "authId": "kCd8oHU8VIcdtzcCbg3ARydWeMl1"
}